# PROJECT METADATA (The Island Root)
name: "Project Phoenix"
description: "Next-gen AI control grid prototype."
created_at: "2024-01-03"
status: "In Progress"

# RELATIONS (Implicit Creation)
# The Daemon will check if these exist in SQL. If not, it creates them.
client: "Cyberdyne Systems"
operator: "Arnold S."
lead_dev: "Sarah C."

# TAGS (For Graph/Vector Search)
tags:
  - "AI"
  - "Rust"
  - "High Security"

